[package]
name = "recursive_descent"
version = "0.1.0"
authors = ["tqma <tqma@trip.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
